### ISSUE TITLE
Support for injecting Fasit config into deployment

### ISSUE THREAD

**Issue by jhrv** [nais/naisd#1]
Need to be able to specify dependencies to Fasit resources and inject these into the deployment. This is used as a service-discovery mechanism.

Example in nais.yaml:
```
fasit:
  - alias: mydb
     type: datasource
  - alias: ...
```
This should result in environment variables/secrets that are known to the developer.

Special resource types such as Credentials and Certificates should be injected as Secrets.

And should allow future extension for specifying which resources are exposed by application as well.
