### ISSUE TITLE
support for mulitple ports in service.yaml

### ISSUE THREAD

**Issue by dagframstad** [nais/naisd#58]
Add support for exposing multiple ports:
example: 
```
spec:
  ports:
  - name: http
    port: 80
    targetPort: 80
  - name: hazelcast
    port: 5701
    targetPort: 5701
```
