### ISSUE TITLE
Resources

### ISSUE THREAD

**Issue by audunstrand** [nais/naisd#6]
We must support resources, both requests and limits
We need both default values and the abiility to set values i nais.yaml

We should append the following to nais.yaml
```
resources: # Optional. See: http://kubernetes.io/docs/user-guide/compute-resources/
  limits:
    cpu: 500m # app will have its cpu usage throttled if exceeding this limit
    memory: 512Mi # app will be killed if exceeding these limits
  requests: # app will be scheduled on nodes with at least this amount resources available
    cpu: 200m
    memory: 256Mi
```
