### ISSUE TITLE
Option to map environment variables to other names

### ISSUE THREAD

**Issue by davidsteinsland** [nais/naisd#66]
**What**:
Ability to map Fasit properties to custom environment variables
**How**:
By specifying a map in `nais.yaml`:
```yaml
propertyMap:
  - map: abac.pdp.endpoint.url
    to: ABAC_URL
  - map: srvfoo_username
    to: ABAC_USERNAME
```
**Why**:
Many Fasit resources are shared among many applications, and you cannot control the naming. If the application expects another property name, we have to do the mapping in the application (runtime).

A typical example is a Spring application which can have it's database configured automatically by providing at least the property `spring.datasource.url` (or `SPRING_DATASOURCE_URL` env var). If the database property is mapped in `nais.yaml`, no more configuration will be needed:

```yaml
propertyMap:
  - map: mydb_url
     to: SPRING_DATASOURCE_URL
  - map: mydb_username
     to: SPRING_DATASOURCE_USERNAME
```

**Comment by gtcno** [comment]
Can we just add a field to the list of used fasit resources:
 alias: mydb
 mapTo: whatever
 resourceType: datasource

I can't see any other usecases except fasit lookup?

**Comment by davidsteinsland** [comment]
A fasit resource can yield multiple properties, so the mapping would have to be explicit.

**Comment by jhrv** [comment]
we have this functionality in the old platform as well, but there the mapping only applies to the alias part of the name. E.g. 

```
<datasource alias="gnalias" mapToProperty="mapped" />
```
would result in the variables mapped.url, mapped.username and mapped.password.

Is this enough to solve your use-case, or do you need control over the whole variable name? 
I agree with @gtcno that we should try to tie the mapping as close to the resource declaration as possible.

**Comment by davidsteinsland** [comment]
Not critical, but this would not support applicationProperties. How does this handle conflicts/duplicate names?

Example:
```yaml
fasitResources: # resources fetched from Fasit
  used:
  - alias: srvapp
    mapToProperty: abac
    resourceType: credential
  - alias: abac.pdp.endpoint
    mapToProperty: abac
    resourceType: restservice
```

Here we're mapping two resources to `abac`, because we want the `username` and `password` properties of `srvapp` and the `url` property of `abac.pdp.endpoint` to map to `ABAC_USERNAME`, `ABAC_PASSWORD` and `ABAC_URL`.
However, it's not all too clear which properties may be set, and we will have to look-up the definition of both `credential` and `restservice` to know whether or not there's a collision in property names.

---

Can the mapping be done like this:

```yaml
fasitResources: # resources fetched from Fasit
  used:
  - alias: srvapp
    propertyMap:
        - username: abac.username
        - password: abac.password
    resourceType: credential
  - alias: abac.pdp.endpoint
    propertyMap:
        - url: abac.url
    resourceType: restservice
```
