### ISSUE TITLE
Fasit property naming collisions when migrating

### ISSUE THREAD

**Issue by joakibj** [nais/naisd#72]
Existings apps registered in Fasit typically have two dependencies:
`srv<app>`- certificate
`srv<app>` - credential

This is the naming convention that is set when ordering these resources from Basta.

However, when defining both in the nais.yaml, the last resource is applied, even if the propertyMap defines different names for the ENV.

E.g.:
```
  - alias: srvdokprod
    resourceType: credential
    propertyMap:
      username: SERVICEUSER_USERNAME
      password: SERVICEUSER_PASSWORD
  - alias: srvdokprod
    resourceType: certificate
    propertyMap:
      keystorealias: SRVDOKPROD_CERT_KEYSTOREALIAS
      password: SRVDOKPROD_CERT_PASSWORD
```
In this example, the certificate password is mapped to both `SERVICEUSER_PASSWORD` and `SRVDOKPROD_CERT_PASSWORD` since both resourceTypes have the password property. This shortcoming is also not detectable until runtime, when apps start getting traffic.

We would like to be able to pull in identically named resources and map them to their respective properties.

A workaround is to rename the certificate fasit alias to something else, but in general we want to avoid that to easy migration.
